CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE TABLE "PhoneWhatsAppRegistry" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PhoneNumber" character varying(20) NOT NULL,
        "HasWhatsApp" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ExpiresAt" timestamp with time zone,
        "CheckedByUserId" integer,
        "ValidationCount" integer NOT NULL,
        CONSTRAINT "PK_PhoneWhatsAppRegistry" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE TABLE "Sessions" (
        "Id" uuid NOT NULL,
        "UserId" integer NOT NULL,
        "RefreshToken" character varying(100) NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
        "IpAddress" character varying(50),
        "UserAgent" character varying(500),
        CONSTRAINT "PK_Sessions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE TABLE "SystemSettings" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Key" character varying(50) NOT NULL,
        "Value" character varying(200) NOT NULL,
        "Description" character varying(500),
        "Category" character varying(50),
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
        "UpdatedAt" timestamp with time zone,
        "UpdatedBy" integer,
        CONSTRAINT "PK_SystemSettings" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE TABLE "Users" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Username" character varying(50) NOT NULL,
        "PasswordHash" character varying(100),
        "FirstName" character varying(100) NOT NULL,
        "LastName" character varying(100),
        "Role" character varying(50) NOT NULL,
        "ModeratorId" integer,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "UpdatedBy" integer,
        "LastLogin" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        "DeletedBy" integer,
        "RestoredAt" timestamp with time zone,
        "RestoredBy" integer,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Users_Users_ModeratorId" FOREIGN KEY ("ModeratorId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE TABLE "WhatsAppSessions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ModeratorUserId" integer NOT NULL,
        "Status" character varying(20),
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
        "CreatedByUserId" integer,
        "LastActivityUserId" integer,
        "LastActivityAt" timestamp with time zone,
        "IsPaused" boolean NOT NULL,
        "PausedAt" timestamp with time zone,
        "PausedBy" integer,
        "PauseReason" character varying(100),
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        "DeletedBy" integer,
        "RestoredAt" timestamp with time zone,
        "RestoredBy" integer,
        "UpdatedAt" timestamp with time zone,
        "UpdatedBy" integer,
        CONSTRAINT "PK_WhatsAppSessions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE TABLE "ExtensionDevices" (
        "Id" uuid NOT NULL,
        "ModeratorUserId" integer NOT NULL,
        "DeviceId" character varying(64) NOT NULL,
        "DeviceName" character varying(100),
        "TokenHash" character varying(128) NOT NULL,
        "ExtensionVersion" character varying(20),
        "UserAgent" character varying(500),
        "TokenExpiresAtUtc" timestamp with time zone NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT (NOW()),
        "LastSeenAtUtc" timestamp with time zone,
        "RevokedAtUtc" timestamp with time zone,
        "RevokedReason" character varying(50),
        CONSTRAINT "PK_ExtensionDevices" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ExtensionDevices_Users_ModeratorUserId" FOREIGN KEY ("ModeratorUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE TABLE "Queues" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "DoctorName" character varying(100) NOT NULL,
        "CreatedBy" integer NOT NULL,
        "ModeratorId" integer NOT NULL,
        "CurrentPosition" integer NOT NULL,
        "EstimatedWaitMinutes" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "UpdatedBy" integer,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        "DeletedBy" integer,
        "RestoredAt" timestamp with time zone,
        "RestoredBy" integer,
        CONSTRAINT "PK_Queues" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Queues_Users_ModeratorId" FOREIGN KEY ("ModeratorId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE TABLE "Quotas" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ModeratorUserId" integer NOT NULL,
        "MessagesQuota" bigint NOT NULL,
        "ConsumedMessages" bigint NOT NULL,
        "QueuesQuota" integer NOT NULL,
        "ConsumedQueues" integer NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedBy" integer,
        "UpdatedBy" integer,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        "DeletedBy" integer,
        "RestoredAt" timestamp with time zone,
        "RestoredBy" integer,
        CONSTRAINT "PK_Quotas" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Quotas_Users_ModeratorUserId" FOREIGN KEY ("ModeratorUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE TABLE "ExtensionPairingCodes" (
        "Id" uuid NOT NULL,
        "ModeratorUserId" integer NOT NULL,
        "Code" character varying(8) NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT (NOW()),
        "ExpiresAtUtc" timestamp with time zone NOT NULL,
        "UsedAtUtc" timestamp with time zone,
        "UsedByDeviceId" uuid,
        CONSTRAINT "PK_ExtensionPairingCodes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ExtensionPairingCodes_ExtensionDevices_UsedByDeviceId" FOREIGN KEY ("UsedByDeviceId") REFERENCES "ExtensionDevices" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_ExtensionPairingCodes_Users_ModeratorUserId" FOREIGN KEY ("ModeratorUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE TABLE "ExtensionSessionLeases" (
        "Id" uuid NOT NULL,
        "ModeratorUserId" integer NOT NULL,
        "DeviceId" uuid NOT NULL,
        "LeaseTokenHash" character varying(128) NOT NULL,
        "AcquiredAtUtc" timestamp with time zone NOT NULL DEFAULT (NOW()),
        "ExpiresAtUtc" timestamp with time zone NOT NULL,
        "LastHeartbeatAtUtc" timestamp with time zone NOT NULL DEFAULT (NOW()),
        "RevokedAtUtc" timestamp with time zone,
        "RevokedReason" character varying(50),
        "CurrentUrl" character varying(500),
        "WhatsAppStatus" character varying(20),
        "LastError" character varying(500),
        CONSTRAINT "PK_ExtensionSessionLeases" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ExtensionSessionLeases_ExtensionDevices_DeviceId" FOREIGN KEY ("DeviceId") REFERENCES "ExtensionDevices" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_ExtensionSessionLeases_Users_ModeratorUserId" FOREIGN KEY ("ModeratorUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE TABLE "MessageSessions" (
        "Id" uuid NOT NULL,
        "QueueId" integer NOT NULL,
        "ModeratorId" integer NOT NULL,
        "UserId" integer NOT NULL,
        "SessionType" character varying(20) NOT NULL,
        "Status" character varying(20) NOT NULL,
        "IsPaused" boolean NOT NULL,
        "TotalMessages" integer NOT NULL,
        "SentMessages" integer NOT NULL,
        "FailedMessages" integer NOT NULL,
        "OngoingMessages" integer NOT NULL,
        "StartTime" timestamp with time zone NOT NULL DEFAULT (NOW()),
        "EndTime" timestamp with time zone,
        "LastUpdated" timestamp with time zone,
        "PausedAt" timestamp with time zone,
        "PausedBy" integer,
        "PauseReason" character varying(100),
        "CorrelationId" uuid,
        "RowVersion" bytea,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        "DeletedBy" integer,
        CONSTRAINT "PK_MessageSessions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_MessageSessions_Queues_QueueId" FOREIGN KEY ("QueueId") REFERENCES "Queues" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_MessageSessions_Users_ModeratorId" FOREIGN KEY ("ModeratorId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE TABLE "Patients" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "QueueId" integer NOT NULL,
        "FullName" character varying(100) NOT NULL,
        "PhoneNumber" character varying(20) NOT NULL,
        "CountryCode" character varying(10) NOT NULL DEFAULT '+20',
        "IsValidWhatsAppNumber" boolean,
        "Position" integer NOT NULL,
        "Status" character varying(20) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedBy" integer,
        "UpdatedAt" timestamp with time zone,
        "UpdatedBy" integer,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        "DeletedBy" integer,
        "RestoredAt" timestamp with time zone,
        "RestoredBy" integer,
        "RowVersion" bytea,
        CONSTRAINT "PK_Patients" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Patients_Queues_QueueId" FOREIGN KEY ("QueueId") REFERENCES "Queues" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE TABLE "ExtensionCommands" (
        "Id" uuid NOT NULL,
        "ModeratorUserId" integer NOT NULL,
        "CommandType" character varying(50) NOT NULL,
        "PayloadJson" text NOT NULL,
        "MessageId" uuid,
        "Status" character varying(20) NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT (NOW()),
        "ExpiresAtUtc" timestamp with time zone NOT NULL,
        "SentAtUtc" timestamp with time zone,
        "AckedAtUtc" timestamp with time zone,
        "CompletedAtUtc" timestamp with time zone,
        "ResultJson" text,
        "ResultStatus" character varying(20),
        "RetryCount" integer NOT NULL,
        "Priority" integer NOT NULL,
        CONSTRAINT "PK_ExtensionCommands" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ExtensionCommands_Users_ModeratorUserId" FOREIGN KEY ("ModeratorUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE TABLE "MessageConditions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TemplateId" integer,
        "QueueId" integer NOT NULL,
        "Operator" character varying(20) NOT NULL,
        "Value" integer,
        "MinValue" integer,
        "MaxValue" integer,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "CreatedBy" integer,
        "UpdatedBy" integer,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        "DeletedBy" integer,
        "RestoredAt" timestamp with time zone,
        "RestoredBy" integer,
        CONSTRAINT "PK_MessageConditions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_MessageConditions_Queues_QueueId" FOREIGN KEY ("QueueId") REFERENCES "Queues" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE TABLE "MessageTemplates" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Title" character varying(100) NOT NULL,
        "Content" character varying(2000) NOT NULL,
        "CreatedBy" integer NOT NULL,
        "ModeratorId" integer NOT NULL,
        "QueueId" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
        "UpdatedAt" timestamp with time zone,
        "MessageConditionId" integer NOT NULL,
        "UpdatedBy" integer,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        "DeletedBy" integer,
        "RestoredAt" timestamp with time zone,
        "RestoredBy" integer,
        CONSTRAINT "PK_MessageTemplates" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_MessageTemplates_MessageConditions_MessageConditionId" FOREIGN KEY ("MessageConditionId") REFERENCES "MessageConditions" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_MessageTemplates_Queues_QueueId" FOREIGN KEY ("QueueId") REFERENCES "Queues" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_MessageTemplates_Users_ModeratorId" FOREIGN KEY ("ModeratorId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE TABLE "Messages" (
        "Id" uuid NOT NULL,
        "Position" integer NOT NULL,
        "CalculatedPosition" integer NOT NULL,
        "FullName" character varying(100) NOT NULL,
        "CountryCode" character varying(10) NOT NULL,
        "PatientPhone" character varying(20) NOT NULL,
        "Content" character varying(2000) NOT NULL,
        "Status" character varying(20) NOT NULL,
        "ErrorMessage" character varying(500),
        "PatientId" integer,
        "TemplateId" integer,
        "QueueId" integer,
        "SenderUserId" integer,
        "ModeratorId" integer,
        "SessionId" character varying(100),
        "CorrelationId" uuid,
        "Attempts" integer NOT NULL,
        "LastAttemptAt" timestamp with time zone,
        "SentAt" timestamp with time zone,
        "CreatedBy" integer,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
        "UpdatedBy" integer,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "IsPaused" boolean NOT NULL,
        "PausedAt" timestamp with time zone,
        "PausedBy" integer,
        "PauseReason" character varying(100),
        "NextAttemptAt" timestamp with time zone,
        "InFlightCommandId" uuid,
        "RowVersion" bytea,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        "DeletedBy" integer,
        CONSTRAINT "PK_Messages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Messages_MessageTemplates_TemplateId" FOREIGN KEY ("TemplateId") REFERENCES "MessageTemplates" ("Id"),
        CONSTRAINT "FK_Messages_Queues_QueueId" FOREIGN KEY ("QueueId") REFERENCES "Queues" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Messages_Users_ModeratorId" FOREIGN KEY ("ModeratorId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    INSERT INTO "SystemSettings" ("Id", "Category", "CreatedAt", "Description", "Key", "UpdatedAt", "UpdatedBy", "Value")
    VALUES (1, 'RateLimit', TIMESTAMPTZ '2026-01-12T00:00:00Z', 'تفعيل تحديد معدل الإرسال بين الرسائل', 'RateLimitEnabled', NULL, NULL, 'true');
    INSERT INTO "SystemSettings" ("Id", "Category", "CreatedAt", "Description", "Key", "UpdatedAt", "UpdatedBy", "Value")
    VALUES (2, 'RateLimit', TIMESTAMPTZ '2026-01-12T00:00:00Z', 'الحد الأدنى للتأخير بين الرسائل (بالثواني)', 'RateLimitMinSeconds', NULL, NULL, '3');
    INSERT INTO "SystemSettings" ("Id", "Category", "CreatedAt", "Description", "Key", "UpdatedAt", "UpdatedBy", "Value")
    VALUES (3, 'RateLimit', TIMESTAMPTZ '2026-01-12T00:00:00Z', 'الحد الأقصى للتأخير بين الرسائل (بالثواني)', 'RateLimitMaxSeconds', NULL, NULL, '7');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE INDEX "IX_ExtensionCommands_MessageId" ON "ExtensionCommands" ("MessageId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE INDEX "IX_ExtensionCommands_ModeratorUserId_Status_Priority_CreatedAt~" ON "ExtensionCommands" ("ModeratorUserId", "Status", "Priority", "CreatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE INDEX "IX_ExtensionCommands_Status_ExpiresAtUtc" ON "ExtensionCommands" ("Status", "ExpiresAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE INDEX "IX_ExtensionDevices_ModeratorUserId" ON "ExtensionDevices" ("ModeratorUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE UNIQUE INDEX "IX_ExtensionDevices_ModeratorUserId_DeviceId" ON "ExtensionDevices" ("ModeratorUserId", "DeviceId") WHERE "RevokedAtUtc" IS NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE INDEX "IX_ExtensionPairingCodes_Code" ON "ExtensionPairingCodes" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE INDEX "IX_ExtensionPairingCodes_ModeratorUserId" ON "ExtensionPairingCodes" ("ModeratorUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE UNIQUE INDEX "IX_ExtensionPairingCodes_UsedByDeviceId" ON "ExtensionPairingCodes" ("UsedByDeviceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE INDEX "IX_ExtensionSessionLeases_DeviceId" ON "ExtensionSessionLeases" ("DeviceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE UNIQUE INDEX "IX_ExtensionSessionLeases_ModeratorUserId" ON "ExtensionSessionLeases" ("ModeratorUserId") WHERE "RevokedAtUtc" IS NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE INDEX "IX_ExtensionSessionLeases_ModeratorUserId_RevokedAtUtc" ON "ExtensionSessionLeases" ("ModeratorUserId", "RevokedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE UNIQUE INDEX "IX_MessageConditions_QueueId_Operator" ON "MessageConditions" ("QueueId", "Operator") WHERE "Operator" = 'DEFAULT';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE INDEX "IX_MessageConditions_TemplateId" ON "MessageConditions" ("TemplateId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE INDEX "IX_Messages_IsPaused_Status" ON "Messages" ("IsPaused", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE INDEX "IX_Messages_ModeratorId" ON "Messages" ("ModeratorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE INDEX "IX_Messages_ModeratorId_Status_IsPaused" ON "Messages" ("ModeratorId", "Status", "IsPaused");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE INDEX "IX_Messages_QueueId" ON "Messages" ("QueueId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE INDEX "IX_Messages_SessionId" ON "Messages" ("SessionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE INDEX "IX_Messages_SessionId_Status_IsPaused_IsDeleted" ON "Messages" ("SessionId", "Status", "IsPaused", "IsDeleted");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE INDEX "IX_Messages_Status_CreatedAt" ON "Messages" ("Status", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE INDEX "IX_Messages_TemplateId" ON "Messages" ("TemplateId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE INDEX "IX_MessageSessions_ModeratorId" ON "MessageSessions" ("ModeratorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE INDEX "IX_MessageSessions_QueueId" ON "MessageSessions" ("QueueId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE INDEX "IX_MessageSessions_Status_StartTime" ON "MessageSessions" ("Status", "StartTime");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE INDEX "IX_MessageTemplates_CreatedBy" ON "MessageTemplates" ("CreatedBy");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE UNIQUE INDEX "IX_MessageTemplates_MessageConditionId" ON "MessageTemplates" ("MessageConditionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE INDEX "IX_MessageTemplates_ModeratorId" ON "MessageTemplates" ("ModeratorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE INDEX "IX_MessageTemplates_QueueId" ON "MessageTemplates" ("QueueId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE INDEX "IX_Patients_QueueId_Position" ON "Patients" ("QueueId", "Position");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE INDEX "IX_PhoneWhatsAppRegistry_ExpiresAt" ON "PhoneWhatsAppRegistry" ("ExpiresAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE UNIQUE INDEX "IX_PhoneWhatsAppRegistry_PhoneNumber" ON "PhoneWhatsAppRegistry" ("PhoneNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE INDEX "IX_Queues_DoctorName" ON "Queues" ("DoctorName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE INDEX "IX_Queues_ModeratorId" ON "Queues" ("ModeratorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE UNIQUE INDEX "IX_Quotas_ModeratorUserId" ON "Quotas" ("ModeratorUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE UNIQUE INDEX "IX_SystemSettings_Key" ON "SystemSettings" ("Key");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE INDEX "IX_Users_ModeratorId" ON "Users" ("ModeratorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE UNIQUE INDEX "IX_Users_Username" ON "Users" ("Username");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    CREATE UNIQUE INDEX "IX_WhatsAppSessions_ModeratorUserId" ON "WhatsAppSessions" ("ModeratorUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    ALTER TABLE "ExtensionCommands" ADD CONSTRAINT "FK_ExtensionCommands_Messages_MessageId" FOREIGN KEY ("MessageId") REFERENCES "Messages" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    ALTER TABLE "MessageConditions" ADD CONSTRAINT "FK_MessageConditions_MessageTemplates_TemplateId" FOREIGN KEY ("TemplateId") REFERENCES "MessageTemplates" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    PERFORM setval(
        pg_get_serial_sequence('"SystemSettings"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "SystemSettings") + 1,
            nextval(pg_get_serial_sequence('"SystemSettings"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127200903_InitialMigration') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260127200903_InitialMigration', '8.0.0');
    END IF;
END $EF$;
COMMIT;

